import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { BillingCycle, FeatureUsageTransactionType, Prisma, PricingAdjustmentScope, PricingAdjustmentType } from '@prisma/client';
import { AuditService } from '../audit/audit.service.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { AdjustmentDto, ConsumeFeatureDto, FeatureAddOnDto, PackageChangeDto, PurchaseAddOnDto, QuoteDto, SubscriptionDto, UpdateFeatureAddOnDto, VehicleCountDto, VehicleTierDto } from './dto/commercial.dto.js';

const D = Prisma.Decimal;
const money = (value: Prisma.Decimal.Value) => new D(value).toDecimalPlaces(2);

@Injectable()
export class CommercialService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}

  async listTiers(packageId: string) { return this.prisma.packageVehicleTierPricing.findMany({ where: { packageId }, orderBy: [{ effectiveFrom: 'desc' }, { minVehicles: 'asc' }] }); }
  async addTier(packageId: string, dto: VehicleTierDto, actorId: string) {
    await this.requirePackage(packageId); this.validateTier(dto); await this.assertNoTierOverlap(packageId, dto);
    const row = await this.prisma.packageVehicleTierPricing.create({ data: { packageId, ...this.tierData(dto) } });
    await this.audit.record({ actorId, action: 'PACKAGE_VEHICLE_TIER_CREATED', entityType: 'PackageVehicleTierPricing', entityId: row.id, newData: { packageId } }); return row;
  }
  async updateTier(id: string, dto: VehicleTierDto, actorId: string) {
    const current = await this.prisma.packageVehicleTierPricing.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Vehicle tier not found.');
    this.validateTier(dto); await this.assertNoTierOverlap(current.packageId, dto, id);
    const row = await this.prisma.packageVehicleTierPricing.update({ where: { id }, data: this.tierData(dto) });
    await this.audit.record({ actorId, action: 'PACKAGE_VEHICLE_TIER_UPDATED', entityType: 'PackageVehicleTierPricing', entityId: id }); return row;
  }
  async deactivateTier(id: string, actorId: string) { const row = await this.prisma.packageVehicleTierPricing.update({ where: { id }, data: { isActive: false } }); await this.audit.record({ actorId, action: 'PACKAGE_VEHICLE_TIER_DEACTIVATED', entityType: 'PackageVehicleTierPricing', entityId: id }); return row; }
  async resolvePackageVehiclePrice(packageId: string, vehicleCount: number, effectiveDate = new Date()) {
    if (vehicleCount < 1) throw new BadRequestException('Vehicle count must be greater than zero.');
    const tier = await this.prisma.packageVehicleTierPricing.findFirst({ where: { packageId, isActive: true, effectiveFrom: { lte: effectiveDate }, OR: [{ effectiveTo: null }, { effectiveTo: { gte: effectiveDate } }], minVehicles: { lte: vehicleCount }, AND: [{ OR: [{ maxVehicles: null }, { maxVehicles: { gte: vehicleCount } }] }] }, orderBy: [{ minVehicles: 'desc' }, { effectiveFrom: 'desc' }] });
    if (!tier) throw new BadRequestException(`No active vehicle-tier pricing is configured for ${vehicleCount} vehicles on this package.`); return tier;
  }
  async calculateSubscriptionPrice(dto: QuoteDto) {
    const effectiveDate = dto.effectiveDate ? new Date(dto.effectiveDate) : new Date(); const pkg = await this.prisma.package.findUnique({ where: { code: dto.packageCode }, include: { features: { where: { isIncluded: true }, include: { feature: true } } } });
    if (!pkg || !pkg.isActive) throw new NotFoundException('Active package not found.'); const tier = await this.resolvePackageVehiclePrice(pkg.id, dto.vehicleCount, effectiveDate);
    const baseRecurringAmount = money(new D(tier.pricePerVehicle).mul(dto.vehicleCount)); const adjustments = await this.activeAdjustments(dto.clientId, effectiveDate, [PricingAdjustmentScope.PACKAGE, PricingAdjustmentScope.TOTAL_INVOICE], pkg.id);
    const recurringAdjustment = this.applyAdjustments(baseRecurringAmount, adjustments); const setupAdjustments = await this.activeAdjustments(dto.clientId, effectiveDate, [PricingAdjustmentScope.SETUP_FEE, PricingAdjustmentScope.TOTAL_INVOICE], pkg.id);
    const setup = this.applyAdjustments(pkg.setupFee, setupAdjustments);
    const availableAddOns = await this.prisma.packageFeatureAddOn.findMany({ where: { packageId: pkg.id, isAvailable: true, featureAddOn: { isActive: true, effectiveFrom: { lte: effectiveDate }, OR: [{ effectiveTo: null }, { effectiveTo: { gte: effectiveDate } }] } }, include: { featureAddOn: { include: { feature: true } } } });
    return { packageCode: pkg.code, packageId: pkg.id, vehicleCount: dto.vehicleCount, billingCycle: dto.billingCycle ?? BillingCycle.MONTHLY, tier: { minVehicles: tier.minVehicles, maxVehicles: tier.maxVehicles, tierMode: tier.tierMode }, pricePerVehicle: tier.pricePerVehicle, baseRecurringAmount, discountAmount: recurringAdjustment.discount, finalRecurringAmount: recurringAdjustment.final, setupFee: setup.final, setupFeeDiscountAmount: setup.discount, currency: tier.currency, includedFeatures: pkg.features.map((link) => ({ featureCode: link.feature.code, featureName: link.feature.name, includedQuantity: link.includedQuantity, resetPeriod: link.resetPeriod, isUnlimited: link.isUnlimited })), availableAddOns: availableAddOns.map(({ featureAddOn }) => ({ id: featureAddOn.id, code: featureAddOn.code, name: featureAddOn.name, featureId: featureAddOn.featureId, quantity: featureAddOn.quantity, salePrice: featureAddOn.salePrice, currency: featureAddOn.currency, validityDays: featureAddOn.validityDays })), adjustments };
  }
  async createSubscription(dto: SubscriptionDto, actorId: string) { const quote = await this.calculateSubscriptionPrice(dto); const startDate = new Date(dto.startDate); const row = await this.prisma.$transaction(async (tx) => { await tx.clientSubscription.updateMany({ where: { clientId: dto.clientId, status: 'ACTIVE' }, data: { status: 'CANCELLED', endDate: startDate } }); const subscription = await tx.clientSubscription.create({ data: { clientId: dto.clientId, packageId: quote.packageId, status: 'ACTIVE', billingCycle: quote.billingCycle, startDate, endDate: dto.endDate ? new Date(dto.endDate) : undefined, vehicleCount: dto.vehicleCount, setupFee: quote.setupFee, pricePerVehicle: quote.pricePerVehicle, recurringAmount: quote.finalRecurringAmount, tierMinVehicles: quote.tier.minVehicles, tierMaxVehicles: quote.tier.maxVehicles, tierMode: quote.tier.tierMode, currency: quote.currency } }); await this.grantPackageAllowances(tx, subscription.id, dto.clientId, quote.packageId, startDate); return subscription; }); await this.audit.record({ clientId: dto.clientId, actorId, action: 'CLIENT_SUBSCRIPTION_CREATED', entityType: 'ClientSubscription', entityId: row.id, newData: { packageId: quote.packageId, vehicleCount: dto.vehicleCount } }); return row; }
  async updateVehicleCount(subscriptionId: string, dto: VehicleCountDto, actorId: string) { const sub = await this.prisma.clientSubscription.findUnique({ where: { id: subscriptionId }, include: { package: true } }); if (!sub) throw new NotFoundException('Subscription not found.'); const quote = await this.calculateSubscriptionPrice({ clientId: sub.clientId, packageCode: sub.package.code, vehicleCount: dto.vehicleCount, billingCycle: sub.billingCycle, effectiveDate: dto.effectiveDate }); const row = await this.prisma.clientSubscription.update({ where: { id: subscriptionId }, data: { vehicleCount: dto.vehicleCount, pricePerVehicle: quote.pricePerVehicle, recurringAmount: quote.finalRecurringAmount, tierMinVehicles: quote.tier.minVehicles, tierMaxVehicles: quote.tier.maxVehicles, tierMode: quote.tier.tierMode } }); await this.audit.record({ clientId: sub.clientId, actorId, action: 'CLIENT_SUBSCRIPTION_VEHICLE_COUNT_UPDATED', entityType: 'ClientSubscription', entityId: subscriptionId }); return row; }
  async getSubscription(id: string) { const row = await this.prisma.clientSubscription.findUnique({ where: { id }, include: { package: true, featureAddOnPurchases: { include: { featureAddOn: true }, orderBy: { purchasedAt: 'desc' } } } }); if (!row) throw new NotFoundException('Subscription not found.'); return row; }
  async listSubscriptions(clientId?: string) { return this.prisma.clientSubscription.findMany({ where: clientId ? { clientId } : {}, include: { client: { select: { id: true, name: true, companyCode: true } }, package: true }, orderBy: [{ status: 'asc' }, { createdAt: 'desc' }] }); }
  async changePackage(subscriptionId: string, dto: PackageChangeDto, actorId: string) { const current = await this.prisma.clientSubscription.findUnique({ where: { id: subscriptionId } }); const pkg = await this.requirePackage(dto.packageId); if (!current) throw new NotFoundException('Subscription not found.'); return this.createSubscription({ clientId: current.clientId, packageCode: pkg.code, vehicleCount: dto.vehicleCount, billingCycle: current.billingCycle, startDate: new Date().toISOString(), effectiveDate: dto.effectiveDate }, actorId); }
  async addAdjustment(dto: AdjustmentDto, actorId: string) { if (dto.validTo && new Date(dto.validTo) <= new Date(dto.validFrom)) throw new BadRequestException('Adjustment end must be after its start.'); const row = await this.prisma.clientPricingAdjustment.create({ data: { ...dto, validFrom: new Date(dto.validFrom), validTo: dto.validTo ? new Date(dto.validTo) : undefined, createdBy: actorId } }); await this.audit.record({ clientId: dto.clientId, actorId, action: 'CLIENT_PRICING_ADJUSTMENT_CREATED', entityType: 'ClientPricingAdjustment', entityId: row.id }); return row; }
  async listAdjustments(clientId?: string) { return this.prisma.clientPricingAdjustment.findMany({ where: clientId ? { clientId } : {}, include: { client: { select: { id: true, name: true, companyCode: true } }, subscription: { select: { id: true, packageId: true } } }, orderBy: { createdAt: 'desc' } }); }
  async createAddOn(dto: FeatureAddOnDto, actorId: string) { this.validateAddOn(dto); const row = await this.prisma.featureAddOn.create({ data: { ...dto, effectiveFrom: new Date(dto.effectiveFrom), effectiveTo: dto.effectiveTo ? new Date(dto.effectiveTo) : undefined } }); await this.audit.record({ actorId, action: 'FEATURE_ADDON_CREATED', entityType: 'FeatureAddOn', entityId: row.id }); return row; }
  async updateAddOn(id: string, dto: UpdateFeatureAddOnDto, actorId: string) { this.validateAddOn(dto); const current = await this.prisma.featureAddOn.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Feature add-on not found.'); const row = await this.prisma.featureAddOn.update({ where: { id }, data: { ...dto, effectiveFrom: new Date(dto.effectiveFrom), effectiveTo: dto.effectiveTo ? new Date(dto.effectiveTo) : null } }); await this.audit.record({ actorId, action: 'FEATURE_ADDON_UPDATED', entityType: 'FeatureAddOn', entityId: id }); return row; }
  async setAddOnActive(id: string, isActive: boolean, actorId: string) { const current = await this.prisma.featureAddOn.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Feature add-on not found.'); const row = await this.prisma.featureAddOn.update({ where: { id }, data: { isActive } }); await this.audit.record({ actorId, action: isActive ? 'FEATURE_ADDON_ACTIVATED' : 'FEATURE_ADDON_DEACTIVATED', entityType: 'FeatureAddOn', entityId: id }); return row; }
  async listAddOns(featureId?: string, packageId?: string) { return packageId ? this.prisma.packageFeatureAddOn.findMany({ where: { packageId, isAvailable: true }, include: { featureAddOn: { include: { feature: true } } } }) : this.prisma.featureAddOn.findMany({ where: { ...(featureId ? { featureId } : {}) }, include: { feature: true }, orderBy: { code: 'asc' } }); }
  async setAddOnAvailability(packageId: string, featureAddOnId: string, isAvailable: boolean, actorId: string) { const row = await this.prisma.packageFeatureAddOn.upsert({ where: { packageId_featureAddOnId: { packageId, featureAddOnId } }, create: { packageId, featureAddOnId, isAvailable }, update: { isAvailable } }); await this.audit.record({ actorId, action: 'PACKAGE_FEATURE_ADDON_AVAILABILITY_UPDATED', entityType: 'PackageFeatureAddOn', entityId: row.id }); return row; }
  async purchaseAddOn(clientId: string, dto: PurchaseAddOnDto, actorId: string) { const now = new Date(); const sub = await this.prisma.clientSubscription.findFirst({ where: { id: dto.subscriptionId, clientId, status: 'ACTIVE' } }); if (!sub) throw new NotFoundException('Active subscription not found.'); const availability = await this.prisma.packageFeatureAddOn.findFirst({ where: { packageId: sub.packageId, featureAddOnId: dto.featureAddOnId, isAvailable: true }, include: { featureAddOn: true } }); if (!availability || !availability.featureAddOn.isActive || availability.featureAddOn.effectiveFrom > now || (availability.featureAddOn.effectiveTo && availability.featureAddOn.effectiveTo < now)) throw new BadRequestException('This add-on is not available for the client package.'); const addOn = availability.featureAddOn; const adjustments = await this.activeAdjustments(clientId, now, [PricingAdjustmentScope.FEATURE_ADDON], addOn.id); const commercialPrice = this.applyAdjustments(addOn.salePrice, adjustments); const expiresAt = addOn.validityDays ? new Date(now.getTime() + addOn.validityDays * 86400000) : null; const purchase = await this.prisma.$transaction(async (tx) => { const row = await tx.clientFeatureAddOnPurchase.create({ data: { clientId, subscriptionId: sub.id, featureAddOnId: addOn.id, featureId: addOn.featureId, quantityPurchased: addOn.quantity, quantityConsumed: 0, quantityRemaining: addOn.quantity, unitPrice: addOn.salePrice, amount: addOn.salePrice, discountAmount: commercialPrice.discount, totalAmount: commercialPrice.final, currency: addOn.currency, purchasedAt: now, validFrom: now, expiresAt, status: 'ACTIVE' } }); const lot = await tx.featureCreditLot.create({ data: { clientId, subscriptionId: sub.id, featureId: addOn.featureId, sourceType: 'FEATURE_ADDON', sourceId: row.id, sourceKey: `purchase:${row.id}`, purchaseId: row.id, quantityOriginal: addOn.quantity, quantityAvailable: addOn.quantity, expiresAt } }); await tx.featureUsageLedger.create({ data: { clientId, subscriptionId: sub.id, featureId: addOn.featureId, creditLotId: lot.id, sourceType: 'FEATURE_ADDON', sourceId: row.id, transactionType: 'CREDIT', quantity: addOn.quantity, referenceType: 'ADDON_PURCHASE', referenceId: row.id, occurredAt: now, expiresAt } }); return row; }); await this.audit.record({ clientId, actorId, action: 'FEATURE_ADDON_PURCHASED', entityType: 'ClientFeatureAddOnPurchase', entityId: purchase.id }); return purchase; }
  async purchaseHistory(clientId: string) { return this.prisma.clientFeatureAddOnPurchase.findMany({ where: { clientId }, include: { featureAddOn: true, feature: true }, orderBy: { purchasedAt: 'desc' } }); }
  async comparePackages(vehicleCount: number, clientId = 'comparison') { const packages = await this.prisma.package.findMany({ where: { isActive: true, isCustom: false }, orderBy: { displayOrder: 'asc' } }); return Promise.all(packages.map(async (pkg) => { try { return await this.calculateSubscriptionPrice({ clientId, packageCode: pkg.code, vehicleCount }); } catch (error) { return { packageCode: pkg.code, configurationError: error instanceof Error ? error.message : 'Pricing configuration error' }; } })); }
  async getAvailableFeatureBalance(clientId: string, featureCode: string) { const feature = await this.prisma.feature.findUnique({ where: { code: featureCode } }); if (!feature) throw new NotFoundException('Feature not found.'); const now = new Date(); const aggregate = await this.prisma.featureCreditLot.aggregate({ where: { clientId, featureId: feature.id, quantityAvailable: { gt: 0 }, OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] }, _sum: { quantityAvailable: true } }); return { clientId, featureCode, availableQuantity: aggregate._sum?.quantityAvailable ?? new D(0) }; }
  async consumeFeatureUsage(clientId: string, dto: ConsumeFeatureDto, actorId?: string) { const feature = await this.prisma.feature.findUnique({ where: { code: dto.featureCode } }); if (!feature) throw new NotFoundException('Feature not found.'); const now = new Date(); const required = new D(dto.quantity); return this.prisma.$transaction(async (tx) => { const lots = await tx.$queryRaw<Array<{ id: string; quantityAvailable: Prisma.Decimal; sourceType: 'PACKAGE_ALLOWANCE' | 'FEATURE_ADDON' | 'MANUAL_ADJUSTMENT' | 'PROMOTIONAL_CREDIT'; sourceId: string | null; purchaseId: string | null }>>(Prisma.sql`SELECT "id", "quantityAvailable", "sourceType", "sourceId", "purchaseId" FROM "FeatureCreditLot" WHERE "clientId" = ${clientId} AND "featureId" = ${feature.id} AND "quantityAvailable" > 0 AND ("expiresAt" IS NULL OR "expiresAt" > ${now}) ORDER BY CASE WHEN "expiresAt" IS NULL THEN 1 ELSE 0 END, "expiresAt" ASC FOR UPDATE`); let remaining = required; if (lots.reduce((sum, lot) => sum.plus(lot.quantityAvailable), new D(0)).lessThan(required)) throw new ConflictException('Insufficient feature balance.'); for (const lot of lots) { if (remaining.isZero()) break; const used = Prisma.Decimal.min(lot.quantityAvailable, remaining); const updated = lot.quantityAvailable.minus(used); await tx.featureCreditLot.update({ where: { id: lot.id }, data: { quantityAvailable: updated } }); if (lot.purchaseId) { const purchase = await tx.clientFeatureAddOnPurchase.update({ where: { id: lot.purchaseId }, data: { quantityConsumed: { increment: used }, quantityRemaining: { decrement: used } } }); if (purchase.quantityRemaining.lte(0)) await tx.clientFeatureAddOnPurchase.update({ where: { id: lot.purchaseId }, data: { status: 'CONSUMED', quantityRemaining: 0 } }); } await tx.featureUsageLedger.create({ data: { clientId, subscriptionId: dto.subscriptionId, featureId: feature.id, creditLotId: lot.id, sourceType: lot.sourceType, sourceId: lot.sourceId, transactionType: 'DEBIT', quantity: used.negated(), balanceAfter: updated, referenceType: dto.referenceType, referenceId: dto.referenceId, occurredAt: now, metadata: dto.metadata as Prisma.InputJsonValue | undefined } }); remaining = remaining.minus(used); } if (actorId) await this.audit.record({ clientId, actorId, action: 'FEATURE_USAGE_CONSUMED', entityType: 'FeatureUsageLedger', entityId: dto.referenceId ?? feature.id }); return { consumedQuantity: required, featureCode: dto.featureCode }; }); }
  async usageHistory(clientId: string, featureCode?: string) { const feature = featureCode ? await this.prisma.feature.findUnique({ where: { code: featureCode } }) : null; return this.prisma.featureUsageLedger.findMany({ where: { clientId, ...(feature ? { featureId: feature.id } : {}) }, include: { feature: true }, orderBy: { occurredAt: 'desc' }, take: 250 }); }
  private tierData(dto: VehicleTierDto) { return { minVehicles: dto.minVehicles, maxVehicles: dto.maxVehicles ?? null, pricePerVehicle: dto.pricePerVehicle, currency: dto.currency ?? 'INR', billingPeriod: dto.billingPeriod ?? BillingCycle.MONTHLY, tierMode: dto.tierMode ?? 'VOLUME', effectiveFrom: new Date(dto.effectiveFrom), effectiveTo: dto.effectiveTo ? new Date(dto.effectiveTo) : null, isActive: dto.isActive ?? true }; }
  private validateTier(dto: VehicleTierDto) { if (dto.maxVehicles !== undefined && dto.maxVehicles < dto.minVehicles) throw new BadRequestException('Tier maximum must be greater than or equal to its minimum.'); if (dto.effectiveTo && new Date(dto.effectiveTo) <= new Date(dto.effectiveFrom)) throw new BadRequestException('Tier effective end must be after its start.'); }
  private validateAddOn(dto: FeatureAddOnDto) { if (dto.effectiveTo && new Date(dto.effectiveTo) <= new Date(dto.effectiveFrom)) throw new BadRequestException('Add-on effective end must be after its start.'); }
  private async assertNoTierOverlap(packageId: string, dto: VehicleTierDto, ignoreId?: string) { if (dto.isActive === false) return; const rows = await this.prisma.packageVehicleTierPricing.findMany({ where: { packageId, isActive: true, ...(ignoreId ? { id: { not: ignoreId } } : {}) } }); const from = new Date(dto.effectiveFrom), to = dto.effectiveTo ? new Date(dto.effectiveTo) : null; const overlaps = rows.some((row) => { const dateOverlap = row.effectiveFrom <= (to ?? new Date('9999-12-31')) && (row.effectiveTo ?? new Date('9999-12-31')) >= from; const quantityOverlap = row.minVehicles <= (dto.maxVehicles ?? Number.MAX_SAFE_INTEGER) && (row.maxVehicles ?? Number.MAX_SAFE_INTEGER) >= dto.minVehicles; return dateOverlap && quantityOverlap; }); if (overlaps) throw new ConflictException('Active vehicle-tier ranges cannot overlap for the same package and effective period.'); }
  private async activeAdjustments(clientId: string, date: Date, scopes: PricingAdjustmentScope[], referenceId: string) { return this.prisma.clientPricingAdjustment.findMany({ where: { clientId, isActive: true, adjustmentScope: { in: scopes }, validFrom: { lte: date }, OR: [{ validTo: null }, { validTo: { gte: date } }], AND: [{ OR: [{ referenceId: null }, { referenceId }] }] } }); }
  private applyAdjustments(amount: Prisma.Decimal, adjustments: Array<{ adjustmentType: PricingAdjustmentType; adjustmentValue: Prisma.Decimal }>) { let final = new D(amount); for (const adjustment of adjustments) final = adjustment.adjustmentType === 'PERCENTAGE' ? final.minus(final.mul(adjustment.adjustmentValue).div(100)) : adjustment.adjustmentType === 'FIXED_AMOUNT' ? final.minus(adjustment.adjustmentValue) : new D(adjustment.adjustmentValue); final = Prisma.Decimal.max(final, new D(0)); return { final: money(final), discount: money(new D(amount).minus(final)) }; }
  private async grantPackageAllowances(tx: Prisma.TransactionClient, subscriptionId: string, clientId: string, packageId: string, startsAt: Date) { const features = await tx.packageFeature.findMany({ where: { packageId, isIncluded: true, isUnlimited: false, includedQuantity: { gt: 0 } } }); for (const item of features) { const lot = await tx.featureCreditLot.create({ data: { clientId, subscriptionId, featureId: item.featureId, sourceType: 'PACKAGE_ALLOWANCE', sourceId: item.id, sourceKey: `allowance:${subscriptionId}:${item.id}:${startsAt.toISOString().slice(0, 10)}`, quantityOriginal: item.includedQuantity!, quantityAvailable: item.includedQuantity!, periodStart: startsAt } }); await tx.featureUsageLedger.create({ data: { clientId, subscriptionId, featureId: item.featureId, creditLotId: lot.id, sourceType: 'PACKAGE_ALLOWANCE', sourceId: item.id, transactionType: 'CREDIT', quantity: item.includedQuantity!, referenceType: 'SUBSCRIPTION_START', referenceId: subscriptionId, occurredAt: startsAt } }); } }
  private async requirePackage(id: string) { const pkg = await this.prisma.package.findUnique({ where: { id } }); if (!pkg) throw new NotFoundException('Package not found.'); return pkg; }
}
