-- Package limits use PostgreSQL INT's maximum value as the unlimited sentinel.
-- Existing zero values were generated by the former defaults, so move them to
-- the new unlimited representation before setting the new column defaults.
UPDATE "Package"
SET
  "maxFleets" = CASE WHEN "maxFleets" = 0 THEN 2147483647 ELSE "maxFleets" END,
  "maxRiders" = CASE WHEN "maxRiders" = 0 THEN 2147483647 ELSE "maxRiders" END,
  "maxAdmins" = CASE WHEN "maxAdmins" = 0 THEN 2147483647 ELSE "maxAdmins" END,
  "maxFleetManagers" = CASE WHEN "maxFleetManagers" = 0 THEN 2147483647 ELSE "maxFleetManagers" END,
  "maxHubs" = CASE WHEN "maxHubs" = 0 THEN 2147483647 ELSE "maxHubs" END,
  "maxTeamLeaders" = CASE WHEN "maxTeamLeaders" = 0 THEN 2147483647 ELSE "maxTeamLeaders" END,
  "maxClusterManagers" = CASE WHEN "maxClusterManagers" = 0 THEN 2147483647 ELSE "maxClusterManagers" END,
  "maxUsers" = CASE WHEN "maxUsers" = 0 THEN 2147483647 ELSE "maxUsers" END;

ALTER TABLE "Package"
  ALTER COLUMN "maxFleets" SET DEFAULT 2147483647,
  ALTER COLUMN "maxRiders" SET DEFAULT 2147483647,
  ALTER COLUMN "maxAdmins" SET DEFAULT 2147483647,
  ALTER COLUMN "maxFleetManagers" SET DEFAULT 2147483647,
  ALTER COLUMN "maxHubs" SET DEFAULT 2147483647,
  ALTER COLUMN "maxTeamLeaders" SET DEFAULT 2147483647,
  ALTER COLUMN "maxClusterManagers" SET DEFAULT 2147483647,
  ALTER COLUMN "maxUsers" SET DEFAULT 2147483647;
