ALTER TYPE "FeatureCategory" ADD VALUE IF NOT EXISTS 'LOGIN';
ALTER TYPE "FeatureCategory" ADD VALUE IF NOT EXISTS 'USER_VERIFICATION';
ALTER TYPE "FeatureCategory" ADD VALUE IF NOT EXISTS 'COUPON';
ALTER TYPE "FeatureCategory" ADD VALUE IF NOT EXISTS 'TRAINING';
