// Source of truth: the 47 Feature Pricing records exported from the local
// development database on 2026-09-20. `featureCode` keeps the seed portable.
const effectiveFrom = '2026-09-01';
const defaults = { currency: 'INR', effectiveFrom, effectiveTo: null, isActive: true, metadata: null };

export const featurePricingCatalog = [
  { featureCode: 'AADHAR_PROOF_DOCUMENT', billingUnit: 'UPLOAD', salePrice: 0.4, costPrice: 0.2, ...defaults },
  { featureCode: 'AADHAR_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 8, costPrice: 5, ...defaults },
  { featureCode: 'ADDRESS_PROOF_DOCUMENT', billingUnit: 'UPLOAD', salePrice: 0.2, costPrice: 0.1, ...defaults },
  { featureCode: 'ADDRESS_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 5, costPrice: 2, ...defaults },
  { featureCode: 'AGE_PROOF_DOCUMENT', billingUnit: 'UPLOAD', salePrice: 0.2, costPrice: 0.1, ...defaults },
  { featureCode: 'AGE_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 2, costPrice: 1, ...defaults },
  { featureCode: 'BANK_PROOF_DOCUMENT', billingUnit: 'UPLOAD', salePrice: 0.2, costPrice: 0.1, ...defaults },
  { featureCode: 'BANK_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 5, costPrice: 3, ...defaults },
  { featureCode: 'CAPTRUE_LOGIN_OTP', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_AADHAAR', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_ADDRESS', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_AGE', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_BANK_ACCOUNT', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_DRIVING_LICENSE', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_EMAIL', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_EMERGENCY_CONTACT', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_INSURANCE_NOMINEE', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_MEDICAL_DECLARATION', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_MOBILE_NUMBER', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_NACH_EMANDATE', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_PAN', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_POLICE_VERIFICATION', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_REFERENCE', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_REFERRAL', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'CAPTURE_UPI', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'DRIVING_LICENCE_PROOF_DOCUMENT', billingUnit: 'UPLOAD', salePrice: 0.2, costPrice: 0.1, ...defaults },
  { featureCode: 'DRIVING_LICENCE_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 10, costPrice: 6, ...defaults },
  { featureCode: 'EMAIL_LOGIN_OTP', billingUnit: 'EMAIL', salePrice: 0.25, costPrice: 0.15, ...defaults },
  { featureCode: 'EMERGENCY_CONTACT_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 5, costPrice: 3, ...defaults },
  { featureCode: 'FACE_LIVENESS_CHECK', billingUnit: 'FACE_SCAN', salePrice: 5, costPrice: 3, ...defaults },
  { featureCode: 'INSURANCE_NOMINEE_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 1, costPrice: 0.5, ...defaults },
  { featureCode: 'MEDICAL_PROOF_DOCUMENT', billingUnit: 'UPLOAD', salePrice: 0.75, costPrice: 0.5, ...defaults },
  { featureCode: 'NACH_MANDATE_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 15, costPrice: 10, ...defaults },
  { featureCode: 'PAN_PROOF_DOCUMENT', billingUnit: 'UPLOAD', salePrice: 0.2, costPrice: 0.1, ...defaults },
  { featureCode: 'PAN_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 5, costPrice: 3, ...defaults },
  { featureCode: 'POLICE_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 150, costPrice: 100, ...defaults },
  { featureCode: 'REFERENCE_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 8, costPrice: 5, ...defaults },
  { featureCode: 'REFERRAL_BENEFIT', billingUnit: 'USER', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'SHOW_AGREEMENT_E_SIGN', billingUnit: 'USER', salePrice: 25, costPrice: 18, ...defaults },
  { featureCode: 'SHOW_ON_BOARDING_FEES', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'SHOW_PLAN_SELECTION', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'SHOW_SECURITY_DEPOSIT', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'SHOW_TRAINING', billingUnit: 'LIFE_TIME', salePrice: 1000, costPrice: 500, ...defaults },
  { featureCode: 'SMS_LOGIN_OTP', billingUnit: 'SMS', salePrice: 0.5, costPrice: 0.25, ...defaults },
  { featureCode: 'TRAINING_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 50, costPrice: 30, ...defaults },
  { featureCode: 'UPI_VERIFICATION', billingUnit: 'VERIFICATION', salePrice: 5, costPrice: 3, ...defaults },
  { featureCode: 'UPLOAD_PROFILE_PHOTO', billingUnit: 'UPLOAD', salePrice: 0.3, costPrice: 0.2, ...defaults },
];
