// Imported from the approved Feature List workbook. Keep this catalog
// platform-owned: clients select from it but cannot modify its definitions.
export const featureStepSpecs = [
  { id: '6b48d8ab-f99c-4cc7-bff9-0c6461f654ad', code: 'LOGIN', displayName: 'Login', description: 'Login to the platform.', displayOrder: 1 },
  { id: 'b3998f75-a3eb-5ea7-b481-5c120dcb646d', code: 'RIDER_ONBOARDING', displayName: 'Rider Onboarding', description: 'End-to-end workflow for registering, verifying, training, contracting, and onboarding a rider onto the EVsEye platform.', displayOrder: 2 },
  { id: 'c8b17b1e-8cc5-52f5-817b-5c574e5e7702', code: 'RIDER_PERSONAL_PROFILE', displayName: 'Personal Profile', description: "Captures the rider's basic personal information including name, mobile number, date of birth, address, referral details, and profile photo.", parentCode: 'RIDER_ONBOARDING', displayOrder: 1 },
  { id: 'f54905a5-960c-53ae-b217-ac729b5d832e', code: 'RIDER_KYC', displayName: 'Identity & KYC', description: 'Captures and verifies the rider\'s identity and KYC information including Aadhaar and PAN details.', parentCode: 'RIDER_ONBOARDING', displayOrder: 2 },
  { id: 'b8873752-e220-5a67-af19-6370f4e3a7e3', code: 'RIDER_COMPLIANCE_ELIGIBILITY', displayName: 'Compliance & Eligibility', description: 'Validates rider eligibility and compliance requirements including driving licence, age eligibility, references, emergency contact, and medical declaration.', parentCode: 'RIDER_ONBOARDING', displayOrder: 3 },
  { id: 'c93c138c-e093-574c-8ca4-96c0ee52b027', code: 'RIDER_COMMERCIALS', displayName: 'Commercial & Payment Details', description: 'Captures commercial and payment-related information including bank account, UPI, e-mandate, security deposit, onboarding fee, rental plan, and insurance nominee.', parentCode: 'RIDER_ONBOARDING', displayOrder: 4 },
  { id: '6f4b8d25-257e-5cce-bcd2-750a2cce296a', code: 'RIDER_TRAINING', displayName: 'Training', description: 'Manages mandatory or optional rider training requirements before onboarding completion.', parentCode: 'RIDER_ONBOARDING', displayOrder: 5 },
  { id: '561efbc2-bfa4-587a-8196-3e7b5f99aa85', code: 'RIDER_AGREEMENT_ESIGN', displayName: 'Agreement & E-Sign', description: 'Presents the applicable rider agreement and manages electronic acceptance and e-signature.', parentCode: 'RIDER_ONBOARDING', displayOrder: 6 },
  { id: 'aed53787-da08-5987-8c11-8c714c05e47a', code: 'RIDER_REVIEW_SUBMIT', displayName: 'Review & Submit', description: 'Allows the rider to review entered information, documents, declarations, commercial details, and agreements before final submission.', parentCode: 'RIDER_ONBOARDING', displayOrder: 7 },
  { id: '5edd6806-31f4-5967-a6a3-a3e86136d7b8', code: 'RIDER_ONBOARDING_STATUS', displayName: 'Onboarding Status', description: 'Displays the rider\'s onboarding application status after submission, including verification, approval, rejection, or pending actions.', parentCode: 'RIDER_ONBOARDING', displayOrder: 8 },
];
