// Source of truth: 51 Feature Pricing records exported from the local development database on 2026-09-21.
// featureCode keeps this catalog portable across databases.

export const featurePricingCatalog = [
  {
    "featureCode": "AADHAR_PROOF_DOCUMENT",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.4",
    "costPrice": "0.2",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "AADHAR_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "8",
    "costPrice": "5",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "ADDRESS_PROOF_DOCUMENT",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.2",
    "costPrice": "0.1",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "ADDRESS_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "5",
    "costPrice": "2",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "AGE_PROOF_DOCUMENT",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.2",
    "costPrice": "0.1",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "AGE_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "2",
    "costPrice": "1",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "BANK_PROOF_DOCUMENT",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.2",
    "costPrice": "0.1",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "BANK_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "5",
    "costPrice": "3",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTRUE_LOGIN_OTP",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_AADHAAR",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_ADDRESS",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_AGE",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_BANK_ACCOUNT",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_DRIVING_LICENSE",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_EMAIL",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_EMERGENCY_CONTACT",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_FULL_NAME",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_INSURANCE_NOMINEE",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_MEDICAL_DECLARATION",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_MOBILE_NUMBER",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_NACH_EMANDATE",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_PAN",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_POLICE_VERIFICATION",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_REFERENCE",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_REFERRAL",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "CAPTURE_UPI",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "DRIVING_LICENCE_PROOF_DOCUMENT",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.2",
    "costPrice": "0.1",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "DRIVING_LICENCE_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "10",
    "costPrice": "6",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "EMAIL_LOGIN_OTP",
    "billingUnit": "EMAIL",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.25",
    "costPrice": "0.15",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "EMERGENCY_CONTACT_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "5",
    "costPrice": "3",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "FACE_LIVENESS_CHECK",
    "billingUnit": "FACE_SCAN",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "5",
    "costPrice": "3",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "INSURANCE_NOMINEE_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1",
    "costPrice": "0.5",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "MEDICAL_PROOF_DOCUMENT",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.75",
    "costPrice": "0.5",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "NACH_MANDATE_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "15",
    "costPrice": "10",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "PAN_PROOF_DOCUMENT",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.2",
    "costPrice": "0.1",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "PAN_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "5",
    "costPrice": "3",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "POLICE_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "150",
    "costPrice": "100",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "REFERENCE_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "8",
    "costPrice": "5",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "REFERRAL_BENEFIT",
    "billingUnit": "USER",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "SHOW_AGREEMENT_E_SIGN",
    "billingUnit": "USER",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "25",
    "costPrice": "18",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "SHOW_MOBILE_NUMBER",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "SHOW_ON_BOARDING_FEES",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "SHOW_PLAN_SELECTION",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "SHOW_SECURITY_DEPOSIT",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "SHOW_TRAINING",
    "billingUnit": "LIFE_TIME",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "1000",
    "costPrice": "500",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "SMS_LOGIN_OTP",
    "billingUnit": "SMS",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.5",
    "costPrice": "0.25",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "TRAINING_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "50",
    "costPrice": "30",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "UPI_VERIFICATION",
    "billingUnit": "VERIFICATION",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "5",
    "costPrice": "3",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  },
  {
    "featureCode": "UPLOAD_PROFILE_PHOTO",
    "billingUnit": "UPLOAD",
    "currency": "INR",
    "isActive": true,
    "metadata": null,
    "salePrice": "0.3",
    "costPrice": "0.2",
    "effectiveFrom": "2026-09-01T00:00:00.000Z",
    "effectiveTo": null
  }
];
