// Source of truth: 4 Package records exported from the local development database on 2026-09-21.
// MAX_INT (2147483647) represents an unlimited package limit.

export const packageCatalog = [
  {
    "code": "BASIC",
    "name": "Basic",
    "description": "Essential rider onboarding and verification",
    "currency": "INR",
    "maxFleets": 9000,
    "maxRiders": 9000,
    "maxAdmins": 2,
    "maxFleetManagers": 3,
    "maxHubs": 3,
    "maxTeamLeaders": 10,
    "maxClusterManagers": 2,
    "maxUsers": 10000,
    "trialDays": 0,
    "displayOrder": 1,
    "isCustom": false,
    "isActive": true,
    "setupFee": "50000"
  },
  {
    "code": "STANDARD",
    "name": "Standard",
    "description": "Basic features plus rider training",
    "currency": "INR",
    "maxFleets": 19000,
    "maxRiders": 19000,
    "maxAdmins": 5,
    "maxFleetManagers": 10,
    "maxHubs": 10,
    "maxTeamLeaders": 50,
    "maxClusterManagers": 20,
    "maxUsers": 20000,
    "trialDays": 0,
    "displayOrder": 2,
    "isCustom": false,
    "isActive": true,
    "setupFee": "75000"
  },
  {
    "code": "PREMIUM",
    "name": "Premium",
    "description": "Standard features plus face recognition",
    "currency": "INR",
    "maxFleets": 49000,
    "maxRiders": 49000,
    "maxAdmins": 50,
    "maxFleetManagers": 100,
    "maxHubs": 100,
    "maxTeamLeaders": 250,
    "maxClusterManagers": 150,
    "maxUsers": 50000,
    "trialDays": 0,
    "displayOrder": 3,
    "isCustom": false,
    "isActive": true,
    "setupFee": "100000"
  },
  {
    "code": "CUSTOM",
    "name": "Custom",
    "description": "Custom package configured for enterprise clients",
    "currency": "INR",
    "maxFleets": 2147483647,
    "maxRiders": 2147483647,
    "maxAdmins": 2147483647,
    "maxFleetManagers": 2147483647,
    "maxHubs": 2147483647,
    "maxTeamLeaders": 2147483647,
    "maxClusterManagers": 2147483647,
    "maxUsers": 2147483647,
    "trialDays": 0,
    "displayOrder": 4,
    "isCustom": true,
    "isActive": true,
    "setupFee": "0"
  }
];
