ALTER TABLE "FeatureStep" ADD COLUMN "translations" JSONB;
ALTER TABLE "TrainingContent" ADD COLUMN "translations" JSONB;

UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"राइडर ऑनबोर्डिंग","description":"EVs Eye प्लेटफ़ॉर्म पर राइडर का पंजीकरण, सत्यापन, प्रशिक्षण और ऑनबोर्डिंग।"},"te":{"displayName":"రైడర్ ఆన్‌బోర్డింగ్","description":"EVs Eye ప్లాట్‌ఫారమ్‌లో రైడర్ నమోదు, ధృవీకరణ, శిక్షణ మరియు ఆన్‌బోర్డింగ్ ప్రక్రియ."},"kn":{"displayName":"ರೈಡರ್ ಆನ್‌ಬೋರ್ಡಿಂಗ್","description":"EVs Eye ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ರೈಡರ್ ನೋಂದಣಿ, ಪರಿಶೀಲನೆ, ತರಬೇತಿ ಮತ್ತು ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಪ್ರಕ್ರಿಯೆ."}}'::jsonb WHERE "code" = 'RIDER_ONBOARDING';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"व्यक्तिगत विवरण","description":"राइडर का नाम, मोबाइल नंबर, जन्मतिथि, पता, रेफ़रल और प्रोफ़ाइल फ़ोटो दर्ज करें।"},"te":{"displayName":"వ్యక్తిగత వివరాలు","description":"రైడర్ పేరు, మొబైల్ నంబర్, పుట్టిన తేదీ, చిరునామా, రెఫరల్ మరియు ప్రొఫైల్ ఫోటో నమోదు చేయండి."},"kn":{"displayName":"ವೈಯಕ್ತಿಕ ವಿವರಗಳು","description":"ರೈಡರ್ ಹೆಸರು, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ, ಜನ್ಮ ದಿನಾಂಕ, ವಿಳಾಸ, ರೆಫರಲ್ ಮತ್ತು ಪ್ರೊಫೈಲ್ ಫೋಟೋ ದಾಖಲಿಸಿ."}}'::jsonb WHERE "code" = 'RIDER_PERSONAL_PROFILE';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"पहचान और KYC","description":"आधार और PAN सहित राइडर की पहचान और KYC जानकारी दर्ज और सत्यापित करें।"},"te":{"displayName":"గుర్తింపు మరియు KYC","description":"ఆధార్ మరియు PANతో సహా రైడర్ గుర్తింపు, KYC వివరాలను నమోదు చేసి ధృవీకరించండి."},"kn":{"displayName":"ಗುರುತು ಮತ್ತು KYC","description":"ಆಧಾರ್ ಮತ್ತು PAN ಸೇರಿದಂತೆ ರೈಡರ್ ಗುರುತು ಹಾಗೂ KYC ವಿವರಗಳನ್ನು ದಾಖಲಿಸಿ ಪರಿಶೀಲಿಸಿ."}}'::jsonb WHERE "code" = 'RIDER_KYC';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"अनुपालन और पात्रता","description":"ड्राइविंग लाइसेंस, आयु, संदर्भ, आपातकालीन संपर्क और चिकित्सा घोषणा की जाँच करें।"},"te":{"displayName":"నిబంధనలు మరియు అర్హత","description":"డ్రైవింగ్ లైసెన్స్, వయస్సు, సూచనలు, అత్యవసర సంప్రదింపు మరియు వైద్య ప్రకటనను తనిఖీ చేయండి."},"kn":{"displayName":"ಅನುಸರಣೆ ಮತ್ತು ಅರ್ಹತೆ","description":"ಚಾಲನಾ ಪರವಾನಗಿ, ವಯಸ್ಸು, ಉಲ್ಲೇಖಗಳು, ತುರ್ತು ಸಂಪರ್ಕ ಮತ್ತು ವೈದ್ಯಕೀಯ ಘೋಷಣೆಯನ್ನು ಪರಿಶೀಲಿಸಿ."}}'::jsonb WHERE "code" = 'RIDER_COMPLIANCE_ELIGIBILITY';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"वाणिज्यिक और भुगतान विवरण","description":"बैंक खाता, UPI, ई-मैंडेट, जमा राशि, ऑनबोर्डिंग शुल्क और बीमा नामित व्यक्ति का विवरण दर्ज करें।"},"te":{"displayName":"వాణిజ్య మరియు చెల్లింపు వివరాలు","description":"బ్యాంకు ఖాతా, UPI, ఈ-మాండేట్, డిపాజిట్, ఆన్‌బోర్డింగ్ రుసుము మరియు బీమా నామినీ వివరాలను నమోదు చేయండి."},"kn":{"displayName":"ವಾಣಿಜ್ಯ ಮತ್ತು ಪಾವತಿ ವಿವರಗಳು","description":"ಬ್ಯಾಂಕ್ ಖಾತೆ, UPI, ಇ-ಮ್ಯಾಂಡೇಟ್, ಠೇವಣಿ, ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಶುಲ್ಕ ಮತ್ತು ವಿಮಾ ನಾಮಿನಿ ವಿವರಗಳನ್ನು ದಾಖಲಿಸಿ."}}'::jsonb WHERE "code" = 'RIDER_COMMERCIALS';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"प्रशिक्षण","description":"ऑनबोर्डिंग पूरी करने से पहले आवश्यक राइडर प्रशिक्षण पूरा करें।"},"te":{"displayName":"శిక్షణ","description":"ఆన్‌బోర్డింగ్ పూర్తికి ముందు అవసరమైన రైడర్ శిక్షణను పూర్తి చేయండి."},"kn":{"displayName":"ತರಬೇತಿ","description":"ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಮುಗಿಸುವ ಮೊದಲು ಅಗತ್ಯ ರೈಡರ್ ತರಬೇತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ."}}'::jsonb WHERE "code" = 'RIDER_TRAINING';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"समझौता और ई-हस्ताक्षर","description":"राइडर समझौते की समीक्षा करें और इलेक्ट्रॉनिक स्वीकृति या हस्ताक्षर पूरा करें।"},"te":{"displayName":"ఒప్పందం మరియు ఈ-సంతకం","description":"రైడర్ ఒప్పందాన్ని సమీక్షించి ఎలక్ట్రానిక్ అంగీకారం లేదా సంతకం పూర్తి చేయండి."},"kn":{"displayName":"ಒಪ್ಪಂದ ಮತ್ತು ಇ-ಸಹಿ","description":"ರೈಡರ್ ಒಪ್ಪಂದವನ್ನು ಪರಿಶೀಲಿಸಿ ವಿದ್ಯುನ್ಮಾನ ಒಪ್ಪಿಗೆ ಅಥವಾ ಸಹಿ ಪೂರ್ಣಗೊಳಿಸಿ."}}'::jsonb WHERE "code" = 'RIDER_AGREEMENT_ESIGN';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"समीक्षा और जमा करें","description":"अंतिम जमा करने से पहले दर्ज जानकारी, दस्तावेज़ और घोषणाओं की समीक्षा करें।"},"te":{"displayName":"సమీక్షించి సమర్పించండి","description":"చివరిగా సమర్పించే ముందు నమోదు చేసిన వివరాలు, పత్రాలు మరియు ప్రకటనలను సమీక్షించండి."},"kn":{"displayName":"ಪರಿಶೀಲಿಸಿ ಸಲ್ಲಿಸಿ","description":"ಅಂತಿಮ ಸಲ್ಲಿಕೆಗೆ ಮೊದಲು ದಾಖಲಿಸಿದ ಮಾಹಿತಿ, ದಾಖಲೆಗಳು ಮತ್ತು ಘೋಷಣೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ."}}'::jsonb WHERE "code" = 'RIDER_REVIEW_SUBMIT';
UPDATE "FeatureStep" SET "translations" = '{"hi":{"displayName":"ऑनबोर्डिंग स्थिति","description":"जमा करने के बाद सत्यापन, स्वीकृति या लंबित कार्रवाई की स्थिति देखें।"},"te":{"displayName":"ఆన్‌బోర్డింగ్ స్థితి","description":"సమర్పించిన తర్వాత ధృవీకరణ, ఆమోదం లేదా పెండింగ్ చర్యల స్థితిని చూడండి."},"kn":{"displayName":"ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಸ್ಥಿತಿ","description":"ಸಲ್ಲಿಕೆಯ ನಂತರ ಪರಿಶೀಲನೆ, ಅನುಮೋದನೆ ಅಥವಾ ಬಾಕಿ ಕ್ರಮಗಳ ಸ್ಥಿತಿಯನ್ನು ನೋಡಿ."}}'::jsonb WHERE "code" = 'RIDER_ONBOARDING_STATUS';
