ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'BATTERY';
ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'CONTROLLER';
ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'IOT_DEVICE';
